export default [
    {
        name: "GitHub",
        link: "https://github.com/Higao00",
        logo: "https://drive.google.com/uc?id=1ugBrl4blIZlr6WSQhx-DnqtO0R0fSzt5",
        qrcode: "https://drive.google.com/uc?id=1OKBj0y3kDuanlV4Q4l0VM7yCzHks-T2i",
        type: "social",
        color: "#adadadeb",
    },
    {
        name: "Linkedin",
        link: "https://www.linkedin.com/in/higor-henrique-89105a187",
        logo: "https://drive.google.com/uc?id=1ocNL1T1TiY28Ewt0-QNpMACi1AcR-Zlq",
        qrcode: "https://drive.google.com/uc?id=1GZ9JtjEZpWkTkDzaNoHrorHcT83_gbSz",
        type: "social",
        color: "#0a66c2",
    },
    {
        name: "Instagram",
        link: "https://www.instagram.com/higao_freitas",
        logo: "https://drive.google.com/uc?id=1AlGenjxqKyF8QMqN0rC01mDPS8IiIzzq",
        qrcode: "https://drive.google.com/uc?id=1RZro4jnmuD6QIS6NzMHMwPKi8ViiFE7Q",
        type: "social",
        color: "#c44564",
    },
    {
        name: "Fecebook",
        link: "https://www.facebook.com/higor.henrique.560",
        logo: "https://drive.google.com/uc?id=1YF2PF_SHDVrZpGy7G_W4TsQFzDULb1Hn",
        qrcode: "https://drive.google.com/uc?id=15qHjmfuBRT1bDPrAxzxDzgQ7j8KL7a4S",
        type: "social",
        color: "#2374E1",
    },
    {
        name: "Outlook",
        link: "freitashigor@hotmail.com",
        logo: "https://drive.google.com/uc?id=1kGJEcdf_IvxGTKSWr4SlrwnTcN6fRom4",
        qrcode: "https://drive.google.com/uc?id=1gAfqj3NbsqtGp6W96yXV2_uONPh7F38w",
        type: "email",
        color: "#016bbb",
    },
    {
        name: "Gmail",
        link: "freitashigor16@gmail.com",
        logo: "https://drive.google.com/uc?id=187R04nYhq8tDG8kvXdxg_d7p04NdYaG6",
        qrcode: "https://drive.google.com/uc?id=1gr6pdLZj_QgViZV_h-ZQUspJEGcwzXH7",
        type: "email",
        color: "#fbbc04",
    },
]
